#!/usr/bin/env bash
# Installs nginx and configures to listen to port 80

sudo apt-get -y update
sudo apt-get -y nginx
echo 'Hello World!' > /var/html/index.nginx-debian.html
sudo service start nginx
