#!/usr/bin/env bash
# Script configuring a new Ubuntu machine

sudo apt-get -y update
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
string_for_replacement="server_name _;\n\typewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
