#!/usr/bin/env bash
# Script configuring Nginx server to have a custom 404 page

sudo apt-get -y update
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
string for replacement="server_name _;\n\typewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
