#!/usr/bin/env bash
# A script that configure Nginx server to have a custom 404 page that contains the string

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo 'Ceci n'"'"'est pas une page' | sudo tee /var/www/html/404_custom_page.html > /dev/null
sudo sed -i 's/#error_page 404/error_page 404 /404_custom_page.html;/g' /etc/nginx/sites-available/default
sudo service nginx restart
