#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm

# Installing HAproxy 
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install haproxy=2.6.\*

# Configuration of HAproxy
server_config=\
"
frontend jedidah-frontend
	bind *:80
	mode http
	default_backend jedidah-backend
backend jedidah-backend
        balance roundrobin
        server web-01 54.173.88.18:80 check
        server web-02 34.239.207.149:80 check
"

echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
