#!/usr/bin/env bash
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm

sudo apt-get -y update
apt-get -y install haproxy

# Configuration of HAproxy
server_config=\
"
frontend  jedidah-frontend
        bind *:80
        mode http
        default_backend jedidah-backend
backend jedidah-backend
        balance roundrobin
        server 169506-web-01 54.173.88.18:80 check
        server 169506-web-02 34.239.207.149:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
